image: node:onbuild

before_script:
  - npm config set loglevel warn
  - npm install --unsafe-perm
  - npm run build

test_integration:
  script:
    - npm run create-conf-from-env
    - mv config.json ./build/
    - npm install -g http-server
    - http-server ./build -p 9080 &
    - npm install -g phantomjs-prebuilt
    - phantomjs -w &
    - sleep 1
    - git clone git@git.rnd.alterway.fr:aic-documentation/aic_features.git
    - cd aic_features
    - npm install --unsafe-perm
    - echo ${AIC_SCREENSHOT_PATH}
    - AIC_FRONTEND_HOST=http://localhost:9080/ ./run-tests.sh
  artifacts:
    paths:
    - ${AIC_SCREENSHOT_PATH}
  except:
    - tags

test_coverage:
  script:
    - npm run coverage
  except:
    - tags

release-job:
  script:
    - echo "release"
  artifacts:
    paths:
    - build
  only:
    - tags