image: node:onbuild

before_script:
  - node --version
  - npm --version
  - npm install --unsafe-perm

test_integration:
  script:
    - npm run build
    - npm run create-conf-from-env
    - mv config.json ./build/
    - ./node_modules/.bin/http-server ./build -p 9080 &
    - git clone git@git.rnd.alterway.fr:aic-documentation/aic_features.git
    - cd aic_features
    - ln -s ../node_modules/
    - npm install --unsafe-perm
    - ./node_modules/.bin/phantomjs --ignore-ssl-errors=true -w &
    - sleep 1
    - echo ${AIC_SCREENSHOT_PATH}
    - AIC_FRONTEND_HOST=http://localhost:9080/ ./run-tests.sh
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
    - ${AIC_SCREENSHOT_PATH}
  except:
    - tags

test_unit:
  script:
    - npm test
  cache:
    paths:
      - node_modules
  except:
    - tags

release-job:
  script:
    - echo "release"
  artifacts:
    paths:
    - build
  only:
    - tags