image: node:onbuild

before_script:
  - npm install --unsafe-perm
  - npm run create-conf-from-env
  - npm run build
  - mv config.json ./build/
  - npm install -g http-server
  - http-server ./build -p 9080 &

test_integration:
  script:
    - npm install -g phantomjs
    - phantomjs -w &
    - sleep 1
    - git clone git@git.rnd.alterway.fr:aic-documentation/aic_features.git
    - cd aic_features
    - npm install --unsafe-perm
    - echo ${AIC_SCREENSHOT_PATH}
    - AIC_FRONTEND_HOST=http://localhost:9080/ ./run-tests.sh
  artifacts:
    paths:
    - ${AIC_SCREENSHOT_PATH}

test_coverage:
  script:
    - npm run coverage