stages:
  - build_&_test_unit     # done for all commits
  - deploy_dev            # only master & dev
  - test_integration      # only master & dev
  - deploy_prod_&_release # deploy_prod => only master; release => only master & tags

job_build:
  image: node:onbuild
  stage: build_&_test_unit
  script:
    - node --version
    - npm --version
    - npm install --unsafe-perm --production
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - build

job_test_unit:
  image: node:onbuild
  stage: build_&_test_unit
  script:
    - node --version
    - npm --version
    - npm install --unsafe-perm
    - npm test
  cache:
    paths:
      - node_modules

job_deploy_dev:
  stage: deploy_dev
  script:
    - echo "deploying dev"
    - scp -r build aicdeploy@$AIC_DEV_HOST:aic/services/artifacts/frontend
    - ssh aicdeploy@$AIC_DEV_HOST
    - ln -s ~/aic/services/frontend-config.json ~/aic/services/artifacts/frontend/config.json
  only:
    - dev
    - master

job_test_integration:
  image: node:onbuild
  stage: test_integration
  script:
    - node --version
    - npm --version
    - git clone git@git.rnd.alterway.fr:aic-documentation/aic_features.git
    - cd aic_features
    - ln -s ../node_modules/
    - npm install --unsafe-perm
    - npm run start-phantomjs &
    - sleep 1
    - echo ${AIC_SCREENSHOT_PATH}
    - AIC_FRONTEND_HOST=${AIC_DEV_HOST} ./run-tests.sh
  # cache:
  #   paths:
  #     - node_modules
  artifacts:
    expire_in: 1 day
    paths:
      - ${AIC_SCREENSHOT_PATH}
  only:
    - dev
    - master

# Rework this job once https://gitlab.com/gitlab-org/gitlab-ce/issues/19208 lands
job_release:
  stage: deploy_prod_&_release
  script:
    - echo "release"
  artifacts:
    expire_in: 3 months
    paths:
    - build
  only:
    - master
    - tags

job_deploy_prod:
  stage: deploy_prod_&_release
  script:
    - echo "tbd"
  only:
    - master

