before_script:
  - npm install --unsafe-perm
  - npm run create-conf-from-env
  - npm run build
  - mv config.json ./build/
  - npm install -g http-server
  - npm install -g phantomjs

test_integration:
  script:
    - http-server ./build -p 9080 &
    - phantomjs -w &
    - sleep 1
    - npm run test-integration-phantom

test_coverage:
  script:
    - http-server ./build -p 9080 &
    - phantomjs -w &
    - sleep 1
    - npm run coverage